name: CI Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Cache .venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-py${{ matrix.python-version }}-
            venv-${{ runner.os }}-
      - name: UV lock file
        run: uv lock
      - name: Install platform dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libdbus-1-dev build-essential libpython3-dev freeglut3-dev libxkbcommon-x11-0 libxcb-cursor0 libegl1 libgl1
      - name: Install dependencies
        run: uv sync --group dev
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: env QT_DEBUG_PLUGINS=1 uv run pytest -v tests/
