name: Build Release

on:
  push:
    tags-ignore:
      - pre*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]
        poetry-version: [ 1.1.7 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install platform dependencies
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt install libdbus-1-dev build-essential libpython3-dev qt5-default
      - name: Install dependencies (Linux)
        run: poetry install -E linux
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: poetry run pytest -v tests/
      - name: Build
        run: poetry build
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: dist/*.tar.gz,dist/*.whl
          token: ${{ secrets.GITHUB_TOKEN }}
