name: Build Release

on:
  push:
    tags-ignore:
      - pre*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.13' ]
        poetry-version: [ '2.1.1' ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set varaiables
        id: var
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install platform dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libdbus-1-dev build-essential libpython3-dev freeglut3-dev
      - name: Poetry lock file
        run: poetry lock
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: poetry run pytest -v tests/
      - name: Build
        run: poetry build
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: dist/*.tar.gz,dist/*.whl
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
      - name: Telegram notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          debug: true
          format: markdown
          disable_web_page_preview: true
          message: |
            *FastOCR ${{ steps.var.outputs.version }} released*

            Check out:
            [Release page](https://github.com/BruceZhang1993/FastOCR/releases/tag/${{ steps.var.outputs.version }})
            [PyPI page](https://pypi.org/project/fastocr/${{ steps.var.outputs.version }}/)

            Wheel package here
          document: dist/fastocr-$GITHUB_VERSION-py3-none-any.whl
